"""
modules.direct_forward package — public API re-exports from sub-modules.

This package replaces the original modules/direct_forward.py (2446 lines).
All original import paths continue to work unchanged.
"""

from .state import (
    STATE_FILE,
    IG_SESSION_FILE,
    _load_state,
    _cursor,
    _bump_cursor,
    _STATE_LOCK,
    _merge_state_save,
    _state_save_owned,
    _get_pair,
    _set_pair,
    request_pair_code,
    cancel_pairing,
    unpair_platform,
    set_platform_pair,
    pairing_status,
)

from .common import (
    URL_RE,
    IG_POST_RE,
    TELEGRAM_CAPTION_LIMIT,
    TELEGRAM_TEXT_LIMIT,
    _poll_interval,
    _tt_poll_interval,
    _activity_stamp,
    _NullStatusMessage,
    _chunk_text,
    _compose_caption,
    _send_followups,
    _download_and_deliver,
    _enqueue_relay,
    _fetch_bytes,
    _video_upload_kwargs,
    _x_media_payload_ok,
    _header_lines,
)

from .instagram import (
    _ig_raw_xma_entries,
    _ig_resolve_raw,
    _ig_pk_from_url,
    _ig_native_deliver_once,
    _enqueue_ig_relay,
    _ig_resolve_user_id,
    _ig_sessionid_from_jar,
    _ig_login,
    _ig_process_message,
    _ig_pairing_scan,
    _instagram_worker,
)

from .twitter import (
    _x_jar_cookies,
    _x_cookies_signature,
    _x_twid_user_id,
    test_x_connection,
    _x_is_tweet_url,
    _x_deep_find_media_url,
    _x_deep_find_tweet,
    _x_tweet_share_author,
    _x_share_media,
    _x_fetch_auth_bytes,
    _x_fallback_photos,
    _x_process_message,
    _x_process_bridge_line,
    _x_read_inbox,
    _x_fetch_self_messages,
    _x_deliver_share_photos,
    _x_deliver_dm_attachment,
    _x_deliver_tweet,
    _twitter_worker,
)

from .tiktok import (
    _TT_APP_KEY,
    _TT_WS_HOST,
    _TT_WS_BROWSER_UA,
    _TT_PRIME_WINDOW,
    _pb_varint,
    _pb_ld,
    _pb_uint,
    _pb_str,
    _pb_ext,
    _pb_read_varint,
    _tt_walk,
    _tt_jar_cookies,
    _tt_jar_cookie_header,
    _tt_wid,
    _tt_access_key,
    _tt_ws_url,
    _tt_connect_frame,
    _tt_parse_push,
    _tt_oembed_author,
    _tt_process_message,
    _tt_run_ws,
    _tiktok_worker,
    test_tiktok_connection,
)

from .supervisor import (
    _direct_forward_supervisor,
    start_direct_forward_task,
)

__all__ = [
    # state
    "STATE_FILE",
    "IG_SESSION_FILE",
    "_load_state",
    "_cursor",
    "_bump_cursor",
    "_STATE_LOCK",
    "_merge_state_save",
    "_state_save_owned",
    "_get_pair",
    "_set_pair",
    "request_pair_code",
    "cancel_pairing",
    "unpair_platform",
    "set_platform_pair",
    "pairing_status",
    # common
    "URL_RE",
    "IG_POST_RE",
    "TELEGRAM_CAPTION_LIMIT",
    "TELEGRAM_TEXT_LIMIT",
    "_poll_interval",
    "_tt_poll_interval",
    "_activity_stamp",
    "_NullStatusMessage",
    "_chunk_text",
    "_compose_caption",
    "_send_followups",
    "_download_and_deliver",
    "_enqueue_relay",
    "_fetch_bytes",
    "_video_upload_kwargs",
    "_x_media_payload_ok",
    "_header_lines",
    # instagram
    "_ig_raw_xma_entries",
    "_ig_resolve_raw",
    "_ig_pk_from_url",
    "_ig_native_deliver_once",
    "_enqueue_ig_relay",
    "_ig_resolve_user_id",
    "_ig_sessionid_from_jar",
    "_ig_login",
    "_ig_process_message",
    "_ig_pairing_scan",
    "_instagram_worker",
    # twitter
    "_x_jar_cookies",
    "_x_cookies_signature",
    "_x_twid_user_id",
    "test_x_connection",
    "_x_is_tweet_url",
    "_x_deep_find_media_url",
    "_x_deep_find_tweet",
    "_x_tweet_share_author",
    "_x_share_media",
    "_x_fetch_auth_bytes",
    "_x_fallback_photos",
    "_x_process_message",
    "_x_process_bridge_line",
    "_x_read_inbox",
    "_x_fetch_self_messages",
    "_x_deliver_share_photos",
    "_x_deliver_dm_attachment",
    "_x_deliver_tweet",
    "_twitter_worker",
    # tiktok
    "_TT_APP_KEY",
    "_TT_WS_HOST",
    "_TT_WS_BROWSER_UA",
    "_TT_PRIME_WINDOW",
    "_pb_varint",
    "_pb_ld",
    "_pb_uint",
    "_pb_str",
    "_pb_ext",
    "_pb_read_varint",
    "_tt_walk",
    "_tt_jar_cookies",
    "_tt_jar_cookie_header",
    "_tt_wid",
    "_tt_access_key",
    "_tt_ws_url",
    "_tt_connect_frame",
    "_tt_parse_push",
    "_tt_oembed_author",
    "_tt_process_message",
    "_tt_run_ws",
    "_tiktok_worker",
    "test_tiktok_connection",
    # supervisor
    "_direct_forward_supervisor",
    "start_direct_forward_task",
]