version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: tg_media_bot
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount certificates as read-only!
    environment:
      - PYTHONUNBUFFERED=1