# utils/cookie_refresher.py
"""
Sequential headless cookie refresher — keeps jars warm even when DM is the only user.

Why: Instagram (and X/TikTok/YouTube) rotate session cookies server-side via Set-Cookie.
yt-dlp write-back already captures rotations, but DM-only accounts never trigger yt-dlp,
so their jars go stale and hit `update_risky_contactpoint` / `login_required` after ~7 days.
Headless browser refresh visits the site as a real user, lets Set-Cookie rotate, and
captures the result — same effect as a manual Chrome incognito refresh, but automated.

Resource: 4 GB RAM + 8 GB swap → one Chromium at a time, sequential, not 4 tabs.
Each site: launch -> add_cookies -> goto -> wait -> extract -> close. Peak ~300 MB.
Scheduled every 24h via main.py::auto_refresh_cookies_loop.

Proxy: uses config.PROXY_URL / DIRECT_FORWARD_PROXY if set, same IP as DM worker,
so no impossible-travel flag.
"""
import asyncio
import logging
import os
import time
from typing import List

import config
from utils import cookie_manager

logger = logging.getLogger(__name__)

# Sites to refresh, in order. One at a time.
_SITES = [
    # (cookie_path, homepage_url, wait_selector_hint)
    (config.IG_COOKIES, "https://www.instagram.com/", "nav"),
    (config.X_COOKIES, "https://x.com/home", "body"),
    (config.TT_COOKIES, "https://www.tiktok.com/", "body"),
    (config.YT_COOKIES, "https://www.youtube.com/", "ytd-app"),
]

def _parse_netscape_to_playwright(path: str) -> List[dict]:
    """Read Netscape jar and return playwright cookie dicts."""
    cookies = []
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            for raw in f:
                line = raw.strip()
                if not line or line.startswith("#"):
                    continue
                # Netscape: domain, flag, path, secure, expiration, name, value
                # HttpOnly is encoded as "#HttpOnly_.domain" prefix on domain
                http_only = False
                if line.startswith("#HttpOnly_"):
                    http_only = True
                    line = line[len("#HttpOnly_"):]
                parts = line.split("\t")
                if len(parts) < 7:
                    continue
                domain, _, c_path, secure, exp, name, value = parts[:7]
                try:
                    exp_int = int(exp)
                except:
                    exp_int = -1
                # Playwright expects expires as float seconds, -1 = session
                cookies.append({
                    "name": name,
                    "value": value,
                    "domain": domain.lstrip("."),
                    "path": c_path,
                    "expires": float(exp_int) if exp_int > 0 else -1,
                    "httpOnly": http_only,
                    "secure": secure.upper() == "TRUE",
                    "sameSite": "Lax",
                })
    except Exception as e:
        logger.warning(f"[CookieRefresh] parse {path} failed: {e}")
    return cookies

def _playwright_to_netscape(cookies: List[dict]) -> str:
    """Convert playwright cookies list to Netscape file content."""
    lines = ["# Netscape HTTP Cookie File", "# http://curl.haxx.se/rfc/cookie_spec.html", "# This file was generated by tgbot cookie_refresher"]
    for c in cookies:
        domain = c.get("domain", "")
        # Playwright domain may not have leading dot, but Netscape expects .domain for flag TRUE
        flag = "TRUE"
        if not domain.startswith("."):
            domain = "." + domain if "." in domain else domain
        c_path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        exp = int(c.get("expires", -1))
        if exp < 0:
            exp = int(time.time()) + 365*24*3600
        name = c.get("name", "")
        value = c.get("value", "")
        http_only = c.get("httpOnly", False)
        # HttpOnly prefix
        dfield = f"#HttpOnly_{domain}" if http_only else domain
        # Ensure name/value don't contain tabs/newlines
        name = name.replace("\t", "_").replace("\n", "")
        value = value.replace("\t", "_").replace("\n", "")
        lines.append(f"{dfield}\t{flag}\t{c_path}\t{secure}\t{exp}\t{name}\t{value}")
    return "\n".join(lines) + "\n"

async def _refresh_one(cookie_path: str, url: str, wait_hint: str = None) -> bool:
    """Refresh a single jar via headless Chromium. Returns True if cookies changed and were written."""
    if not os.path.exists(cookie_path) or os.path.getsize(cookie_path) == 0:
        logger.info(f"[CookieRefresh] skip {cookie_path} — missing/empty")
        return False
    # Quick check: if the jar was freshly written via yt-dlp or admin
    # (<24h), skip the OTHER sites to save RAM — but NEVER skip IG here.
    # Instagram's auth is tightly bound to mid/rur/csrftoken rotation, and
    # the only way to capture a fresh rotation is to actually visit the
    # site. The 17:32 cycle (Aug 28) skipped IG with "mtime 6h ago (<20h)"
    # while the session was already stale — that skip is exactly what
    # caused the 30-redirects regression.
    is_ig = cookie_path.endswith("igcookies.txt")
    if not is_ig:
        try:
            mtime = os.path.getmtime(cookie_path)
            if time.time() - mtime < 20*3600:  # 20h, in case 24h loop drifts
                logger.info(f"[CookieRefresh] skip {os.path.basename(cookie_path)} — mtime {int((time.time()-mtime)/3600)}h ago (<20h)")
                return False
        except:
            pass

    playwright_cookies = _parse_netscape_to_playwright(cookie_path)
    if not playwright_cookies:
        logger.warning(f"[CookieRefresh] no parseable cookies in {cookie_path} — skip")
        return False

    # Use proxy if configured (same as DM worker, avoids impossible travel)
    proxy = getattr(config, "DIRECT_FORWARD_PROXY", None) or getattr(config, "PROXY_URL", None)
    proxy_server = None
    if proxy:
        # Playwright expects {"server": "http://host:port", "username":..., "password":...}
        # We pass raw string; aiohttp proxy style "http://user:pass@host:port" works for chromium via --proxy-server
        # Simplification: use http:// prefix
        proxy_server = proxy
        logger.info(f"[CookieRefresh] using proxy for {os.path.basename(cookie_path)}")

    try:
        from playwright.async_api import async_playwright
    except ImportError:
        logger.error("[CookieRefresh] playwright not installed (pip install playwright) — skip")
        return False

    browser = None
    try:
        async with async_playwright() as p:
            # One browser at a time, headless, no-sandbox for VPS
            launch_args = ["--no-sandbox", "--disable-dev-shm-usage", "--disable-gpu"]
            if proxy_server:
                # Playwright proxy is per-browser: use proxy server
                browser = await p.chromium.launch(headless=True, args=launch_args, proxy={"server": proxy_server} if "://" in proxy_server else {"server": f"http://{proxy_server}"})
            else:
                browser = await p.chromium.launch(headless=True, args=launch_args)
            # Single context, single page
            context = await browser.new_context(
                user_agent=getattr(config, "YTDLP_USER_AGENT", "") or "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
                viewport={"width": 1280, "height": 800},
                locale=getattr(config, "IG_DIRECT_LOCALE", "en_US") or "en_US",
            )
            await context.add_cookies(playwright_cookies)
            page = await context.new_page()
            logger.info(f"[CookieRefresh] visiting {url} for {os.path.basename(cookie_path)}...")
            # Goto with timeout 45s
            try:
                await page.goto(url, wait_until="domcontentloaded", timeout=45000)
                # Wait for network idle a bit, but not too long (15s)
                try:
                    await page.wait_for_load_state("networkidle", timeout=15000)
                except:
                    pass
                # Small extra wait for Set-Cookie to settle
                await asyncio.sleep(5)
                # Trigger some JS that may refresh token (scroll)
                try:
                    await page.evaluate("window.scrollBy(0, 200)")
                    await asyncio.sleep(2)
                except:
                    pass
                # Instagram-specific: visit a few authenticated paths so
                # the server issues fresh mid/rur/csrftoken. Just loading
                # the home page often isn't enough — IG only rotates on
                # authed XHRs. /api/v1 web endpoints are the same paths
                # instagrapi hits, so cookies set there are the same ones
                # the DM worker needs.
                if is_ig:
                    for extra_path in ("/explore/", "/accounts/edit/", "/"):
                        try:
                            await page.goto(
                                f"https://www.instagram.com{extra_path}",
                                wait_until="domcontentloaded", timeout=20000)
                            await asyncio.sleep(2)
                        except Exception as e2:
                            logger.info(
                                f"[CookieRefresh] IG extra visit "
                                f"{extra_path} skipped: {e2}")
            except Exception as e:
                logger.warning(f"[CookieRefresh] goto {url} failed: {e} — still trying to extract cookies")

            # Extract all cookies from context (including rotated ones)
            new_cookies = await context.cookies()
            await context.close()
            await browser.close()
            browser = None

            if not new_cookies:
                logger.warning(f"[CookieRefresh] no cookies extracted from {url}")
                return False

            # Compare: did any cookie value/expires change?
            old_map = {(c["name"], c["domain"]): c["value"] for c in playwright_cookies}
            new_map = {(c["name"], c["domain"]): c["value"] for c in new_cookies}
            changed = sum(1 for k, v in new_map.items() if old_map.get(k) != v)
            if changed == 0:
                logger.info(f"[CookieRefresh] {os.path.basename(cookie_path)} — no rotation detected (still fresh)")
                # Still touch mtime via meta to avoid re-checking too soon
                cookie_manager.touch_cookie_success(cookie_path)
                return False

            # Write back as Netscape, via atomic merge (respect 0o444 lock)
            content = _playwright_to_netscape(new_cookies)
            # Use cookie_manager's merge path: write to temp and overlay
            # For headless refresh, we directly replace the real jar (it's more complete than yt-dlp snapshot)
            # Use _write_cookie_jar logic but without validation failure
            from modules.admin.cookies import _write_cookie_jar
            # Map cookie_path to key
            key_map = {
                config.IG_COOKIES: "igcookies",
                config.X_COOKIES: "xcookies",
                config.TT_COOKIES: "ttcookies",
                config.YT_COOKIES: "ytcookies",
            }
            key = key_map.get(cookie_path, "unknown")
            # If key unknown, do direct atomic write
            if key == "unknown":
                # fallback: atomic write + lock
                is_primary = cookie_path in (config.YT_COOKIES, config.IG_COOKIES, config.TT_COOKIES, config.X_COOKIES)
                tmp = f"{cookie_path}.tmp.{os.getpid()}"
                with open(tmp, "w", encoding="utf-8") as f:
                    f.write(content)
                os.replace(tmp, cookie_path)
                if is_primary:
                    try:
                        os.chmod(cookie_path, 0o444)
                    except:
                        pass
                from utils.downloader import _purge_cookie_snapshots
                _purge_cookie_snapshots(cookie_path)
                cookie_manager.touch_cookie_uploaded(cookie_path)
            else:
                # Use existing admin helper (validates, backs up, purges snapshots, touches meta)
                # It expects content with Netscape header, which we have
                _write_cookie_jar(key, cookie_path, content)

            logger.info(f"[CookieRefresh] {os.path.basename(cookie_path)} refreshed via headless ({changed} cookies rotated, {len(new_cookies)} total)")
            # Also clear direct_ig_session.json if IG was refreshed, so next DM login uses fresh sessionid
            if cookie_path == config.IG_COOKIES:
                for stale in ("direct_ig_session.json", "direct_ig_session.json.bak"):
                    try:
                        if os.path.exists(stale):
                            os.remove(stale)
                            logger.info(f"[CookieRefresh] cleared {stale} after IG refresh")
                    except:
                        pass
            return True

    except Exception as e:
        logger.error(f"[CookieRefresh] {os.path.basename(cookie_path)} refresh failed: {e}")
        if browser:
            try:
                await browser.close()
            except:
                pass
        return False
    finally:
        if browser:
            try:
                await browser.close()
            except:
                pass

async def refresh_all_cookies_sequential():
    """Refresh each primary jar one after another (sequential, 1 browser at a time)."""
    logger.info("[CookieRefresh] starting sequential refresh (4 sites, 1 browser at a time, ~5 min total)")
    for cookie_path, url, hint in _SITES:
        try:
            ok = await _refresh_one(cookie_path, url, hint)
            # Small pause between sites to avoid hammering and to let swap settle
            await asyncio.sleep(5)
            # Log result is already in _refresh_one
        except Exception as e:
            logger.error(f"[CookieRefresh] site {url} failed: {e}")
            await asyncio.sleep(5)
    logger.info("[CookieRefresh] sequential refresh cycle complete")

async def auto_refresh_cookies_loop():
    """Background loop: every 24h, refresh all jars sequentially. Enabled via config."""
    # Respect flag: only run if at least one primary jar exists
    if not any(os.path.exists(p) for p, _, _ in _SITES):
        logger.info("[CookieRefresh] no primary jars found — loop disabled")
        return
    # Stagger first run by 5-10 min after boot to avoid competing with DM warmup
    await asyncio.sleep(300 + (hash(os.urandom(4)) % 300))
    while True:
        try:
            await refresh_all_cookies_sequential()
        except Exception as e:
            logger.error(f"[CookieRefresh] cycle failed: {e}")
        # Sleep 24h (with jitter ±1h to avoid exact 24h cadence detection)
        import random
        await asyncio.sleep(24*3600 + random.randint(-3600, 3600))
